---
- name: copy the war file into webapps
  get_url:
    url: https://github.com/rakesh95/applogin/raw/master/target/applogin-1.2.war
    dest: /tmp
    
- name: copy artifact 
  copy:
     src: /tmp/applogin-1.2.war
     dest: /opt/tomcat/latest/webapps/applogin-1.2.war
     owner: tomcat
     group: tomcat
     remote_src: yes
  notify:
          - restart tomcat
# tasks file for deploy
