---
- name: installing packages
  hosts: all
  become: true  
  tasks:
          - name: install git
            apt:
                  name: git
                  state: latest
                  update_cache: yes
          - name: install wget
            apt:
                  name: wgetdfsdsdfds
                  state: present
            ignore_errors: true

          - name: install tree
            apt: 
                  name: tree
                  state: present
